##Set server names
Servers:
    lobby: "&9Lobby"
    survival: "&6Survival Server"
    mining: "&9Mining Server"
    staff: "&4Staff Server"
    ???: "&7Unknown Server"
Messages:
        ##- '%player% (The playes name)'
        ##- '%to% the server they are heading to'
        ##- '%to_clean% the server they are heading to - Without color codes'
        ##- '%from% the server they are coming from'
        ##- '%from_clean% the server they are coming from - Without color codes'
        ##- '%playercount_from% The amount of players where they are coming from.' 
        ##- '%playercount_to% The amount of players where they are heading to.' 
        ##- '%playercount_network% The amount of players on the network.'
        ##- '%displayname% - The custom name the player has.'
    SwapServerMessage: "&6&l%player%&r &7[%from%&7] (%playercount_from%) -> [%to%&7] (%playercount_to%)"
        ##- '%player%: (The playes name)'
        ##- '%server_name%: The name of the server they connected to.'
        ##- '%server_name_clean% The name of the server they connected to - Without color codes'
        ##- '%playercount_server%: The playercount of the server they are on.'
        ##- '%playercount_network%: The playercount of the network.'
        ##- '%displayname% - The custom name the player has.'
    JoinNetworkMessage: "&6%displayname% &7(%player%&7) &6has connected to the network!"
        ##- '%player%: (The playes name)'
        ##- '%server_name%: The name of the server they disconnected from.'
        ##- '%server_name_clean% The name of the server they connected to - Without color codes'
        ##- '%playercount_server%: The playercount of the server they were on.'
        ##- '%playercount_network%: The playercount of the network.'
        ##- '%displayname% - The custom name the player has, according to bungee.'
    LeaveNetworkMessage: "&6%player% &6has disconnected from the network!"
## Configurable Command Messages!
    Commands:
        NoMoreArgumentsNeeded: "No more arguments needed."
        NoPermission: "&cYou do not have the permission to use this command."
        Fakemessage:
            NoArgument: "&6Arguments:\n- &cfakejoin\n- &cfakequit\n- &cfakeswitch&6 (to) (from)\n"
            FakeSwitchNoArgument: "&6Arguments:\n- &cfakejoin\n- &cfakequit\n- &cfakeswitch&6 (to) (from)\n&4Error: Please specify &cTO&4 and &cFROM\n"
            ToggleSilentNoPerm: "&cYou do not have the permission to join the server silently."
            ToggleSilent: "&eYour SilentMode has now been set to &6<state>"
            JoinNotification: "&7[BungeeJoin] You joined the server while silenced.\n&7To have messages automatically enabled for you until\n&7next reboot, use the command &f/fm toggle&7."
        ToggleJoin:
            MissingFirstArgument: "&6Please specify which messages you would like to disable/enable.\n&6Valid arguments are:&f join, leave, switch, all"
            MissingState: "&6Please specify which state you would like to set the message to.\n&6Valid arguments are: &aon &7/ &coff &6or &atrue &7/ &cfalse&f."
            Confirmation: "&6Receive messages for &f<mode>&6 has been set to &f<state>\n&6This will last until the network reboots."
        Reload:
            ConfigReloaded: "Config Reloaded!"
    Misc:
        SilentPrefix: "&7[Silent] "
        ConsoleSilentMoveEvent: "&1Move Event was silenced. <player> <from> -> <to>"
        ConsoleSilentJoinEvent: "&6Join Event was silenced. <player> joined the network."
        ConsoleSilentQuitEvent: "&cQuit Event was silenced. <player> left the network."
Settings:
    ##Should players with the bungeejoinmessages.silent permission be silenced by default?
    ##It will be set to this for all players after a reboot. They can toggle it for themselves with the /fakemessage toggle command
    SilentJoinDefaultState: true
    ##Should the following messages be enabled?
    SwapServerMessageEnabled: true
    JoinNetworkMessageEnabled: true
    LeaveNetworkMessageEnabled: true
    ##Should other players with the bungeejoinmessages.silent permission be notified of players moving silently?
    NotifyAdminsOnSilentMove: true
    
    ##NOTE: These does not affect silenced players. Silenced move messages will be seen by all players with the permission.
    SwapServerMessageViewableBy:
        ##Should the swap server message be seen by the server they swapped to?
        ServerJoined: true
        
        ##Should the swap server message be seen by the server they swapped from?
        ServerLeft: true
        
        ##Should the swap server message be seen by the other servers?
        OtherServer: true
##New in 1.10.0
    JoinNetworkMessageViewableBy:
        ##Should the Join Network message be seen by the server they Joined?
        ServerJoined: true

        ##Should theJoin Network message be seen by the other servers?
        OtherServer: true
    LeaveNetworkMessageViewableBy:
        ##Should the Leave Network message be seen by the server they left?
        ServerLeft: true

        ##Should the Leave Network message be seen by the other servers?
        OtherServer: true
 
    ##Servers in this list will not trigger messages.
    ##Servers listed here are case sensitive. Check your bungee config to see how you have them listed!
    ServerBlacklist:
        - SomeServerName
        - SomeOtherServerName
    ##Should the blacklist list be the only servers allowed to trigger messages? (Reverse the check)
    UseBlacklistAsWhitelist: false
    ##When a player swaps from A to B, which one should we check? JOINED, LEFT, BOTH, ANY
    ##Behaviour will change depending on the blacklist being in blacklist or whitelist mode.
    ##example: If you set this to JOINED: BlacklistMode will prevent the message from going through if the joined server is going through.
    ##                                    WhitelistMode will only allow it if the joined server is in the list.
    ## IF set to ANY or both, ANY of them must be blacklisted/whitelisted, or BOTH of them must ble blacklisted/whitelisted.
    SwapServerMessageRequires: ANY
##New in 1.10.0
    ##IngoreJoinMessagesList - Players on these servers will not see a message when someone joins the network.
    ##The global message will still be triggered if someone joins these servers directly.
    ##Case sensitive!
    IgnoreJoinMessagesList:
        - SomeServerNameThatShouldNotSeeJoinNetworkMessages
        - SomeOtherServerName
    ##IngoreLeaveMessagesList - Players on these servers will not see a message when someone leaves the network.
    ##The global message will still be triggered if someone leaves these servers directly.
    ##Case sensitive!
    IgnoreLeaveMessagesList:
        - SomeServerNameThatShouldNotSeeLeaveNetworkMessages
        - SomeOtherServerName


OtherPlugins:
    PremiumVanish:
        ToggleFakemessageWhenVanishing: true
        RemoveVanishedPlayersFromPlayerCount: true
